export type ButtonClassNameType =
    | 'primary'
    | 'search'
    | 'delete'
    | 'close'
    | 'counter'
    | 'category'
    | 'sort'
    | 'sortArrow'
    | 'closeModal'
    | 'calories'
    | 'size'
    | 'type'
