export type CustomImageClassNameType =
    | 'notFound'
    | 'logo'
    | 'mini'
    | 'basketEmpty'
    | 'basketPizzaCard'
    | 'pizzaCard'
    | 'pizzaIngredient'
    | 'pizzaModalExtraSmall'
    | 'pizzaModalSmall'
    | 'pizzaModalMiddle'
    | 'pizzaModalLarge'
