name: linting
on:
    push:
        branches: [master]
    pull_request:
        branches: [master]
jobs:
    lint:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4
            - name: Set up Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
            - name: install dependencies
              run: npm ci
            - name: check eslint rules
              run: npm run eslint
            - name: check stylelint rules
              run: npm run stylelint
            - name: check prettier rules
              run: npm run prettier
